import {
  Radio,
  Car,
  Sparkles,
  Briefcase,
  Hourglass,
  Laugh,
  UtensilsCrossed,
  Palette,
  Camera,
  GraduationCap,
  PartyPopper,
  Users,
  Tv,
  Gamepad2,
  Baby,
  Landmark,
  Dumbbell,
  Film,
  Music2,
  Newspaper,
  Tent,
  Megaphone,
  Sunset,
  Church,
  Clapperboard,
  FlaskConical,
  ShoppingBag,
  Trophy,
  Plane,
  CloudSun,
  type LucideIcon,
} from "lucide-react";

// 将 iptv-org 全部分类映射到各不相同的图标（键为 iptv-org 分类 id）。
// 覆盖 categories.json 现有全部非 xxx 分类，每个分类图标互不重复；
// 未知/未来新增分类回落 Radio（信号塔，呼应项目调性）。
const CAT_ICON: Record<string, LucideIcon> = {
  auto: Car,
  animation: Sparkles,
  business: Briefcase,
  classic: Hourglass,
  comedy: Laugh,
  cooking: UtensilsCrossed,
  culture: Palette,
  documentary: Camera,
  education: GraduationCap,
  entertainment: PartyPopper,
  family: Users,
  general: Tv,
  interactive: Gamepad2,
  kids: Baby,
  legislative: Landmark,
  lifestyle: Dumbbell,
  movies: Film,
  music: Music2,
  news: Newspaper,
  outdoor: Tent,
  public: Megaphone,
  relax: Sunset,
  religious: Church,
  series: Clapperboard,
  science: FlaskConical,
  shop: ShoppingBag,
  sports: Trophy,
  travel: Plane,
  weather: CloudSun,
};

export function catIcon(id: string): LucideIcon {
  // 兜底图标用 Radio（信号塔），呼应项目调性
  return CAT_ICON[id] ?? Radio;
}
